# NumPy
Numeric Python
* Collection of values
* NumPy arrays are substitute of lists but can not contain different type of data in a single array
* Easy and fast numeric operations

### Usefulness

In [4]:
height = 1.8
weight = 50

In [5]:
bmi = weight / height ** 2

In [6]:
bmi

15.432098765432098

In [10]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [11]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
import numpy as np

In [17]:
#pip! install numpy

In [12]:
np_height = np.array(height)
np_weight = np.array(weight)

In [13]:
np_weight / np_height ** 2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### Difference from lists

In [16]:
np.array([1.0, "is", True])  # Array contains only one type of data

array(['1.0', 'is', 'True'], dtype='<U32')

In [18]:
list_1 = [1, 2, 3]
list_2 = [1, 2, 3]

In [19]:
list_1 + list_2

[1, 2, 3, 1, 2, 3]

In [24]:
summed = [list_1[0] + list_2[0], list_1[1] + list_2[1], list_1[2] + list_2[2]]

In [25]:
summed

[2, 4, 6]

In [28]:
summed = []
for i,v in enumerate(list_1): 
    for j,m in enumerate(list_2):
        if i == j:
            sum_up = v + m
            summed.append(sum_up)
print(summed)

[2, 4, 6]


In [20]:
array_1 = np.array(list_1)  # Arrays adds up the values
array_2 = np.array(list_2)

In [21]:
array_1 + array_2

array([2, 4, 6])

In [29]:
type(array_1)

numpy.ndarray

### 2D NumPy Arrays

In [36]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])

In [37]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [32]:
np_2d.shape

(2, 5)

In [33]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [40]:
np_2d[0][2]

1.71

In [41]:
np_2d[0,2]  # works wither way

1.71

In [42]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [43]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [38]:
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7], [10, 20, 30, 40, 50]])

In [39]:
np_3d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [10.  , 20.  , 30.  , 40.  , 50.  ]])

### Generating datasets

Simulating a dataset of height and weight of all the residents in a city. Suppose the population of this city is 5000.

In [44]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [45]:
height 

array([1.77, 2.12, 2.16, ..., 2.02, 1.52, 1.66])

In [46]:
len(height)

5000

In [47]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [48]:
np_city = np.column_stack((height, weight))

In [49]:
np_city

array([[ 1.77, 87.95],
       [ 2.12, 83.49],
       [ 2.16, 71.98],
       ...,
       [ 2.02, 64.97],
       [ 1.52, 66.68],
       [ 1.66, 67.77]])

##### 1. What are the mean, median, and standard deviation of the height of the people in the city?

In [50]:
np_height = np.array(np_city[:,0])

In [51]:
print(np.mean(np_height))

1.750216


In [52]:
print(np.median(np_height))

1.75


In [53]:
print(np.std(np_height))

0.19753873884380246


##### 2. Is there any correlation between height and weight?

In [54]:
corr = np.corrcoef(np_city[:,0], np_city[:,1])

Correlation: [[1.         0.01213873]
 [0.01213873 1.        ]]


### Exploring AppleStore data file with NumPy array:

In [56]:
from csv import reader

In [64]:
opened_file = open('AppleStore.csv', encoding='utf-8')
read_file = reader(opened_file)
apps_data = list(read_file)

In [65]:
apps = np.array(apps_data)

In [71]:
apps

array([['id', 'track_name', 'size_bytes', ..., 'ipadSc_urls.num',
        'lang.num', 'vpp_lic'],
       ['284882215', 'Facebook', '389879808', ..., '1', '29', '1'],
       ['389801252', 'Instagram', '113954816', ..., '0', '29', '1'],
       ...,
       ['1070052833', 'Go!Go!Cat!', '91468800', ..., '2', '2', '1'],
       ['1081295232', 'Suppin Detective: Expose their true visage!',
        '83026944', ..., '0', '1', '1'],
       ['977965019', 'みんなのお弁当 by クックパッド ~お弁当をレシピ付きで記録・共有~', '51174400',
        ..., '0', '1', '1']], dtype='<U232')

In [72]:
apps_data[0]

['id',
 'track_name',
 'size_bytes',
 'currency',
 'price',
 'rating_count_tot',
 'rating_count_ver',
 'user_rating',
 'user_rating_ver',
 'ver',
 'cont_rating',
 'prime_genre',
 'sup_devices.num',
 'ipadSc_urls.num',
 'lang.num',
 'vpp_lic']

In [69]:
rating = np.array(apps[1:,7])

In [70]:
rating

array(['3.5', '4.5', '4.5', ..., '0', '0', '0'], dtype='<U232')

In [73]:
price = np.array(apps[1:, 4])

In [ ]:
print(np.mean(p))

In [77]:
p =  price.astype(float) # changing data type of numpy array

In [78]:
p

array([0., 0., 0., ..., 0., 0., 0.])

In [79]:
print(np.mean(p))

1.726217868556343


In [81]:
print(np.median(p))

0.0


In [82]:
print(np.std(p))

5.8326005341785105


In [83]:
r =  rating.astype(float)

In [84]:
print(np.mean(r))

3.526955675976101


In [87]:
print(np.corrcoef(apps[1:,4], apps[1:,7]))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U232'), dtype('<U232')) -> None

In [88]:
rating_price = np.column_stack((r, p))

In [89]:
rating_price

array([[3.5, 0. ],
       [4.5, 0. ],
       [4.5, 0. ],
       ...,
       [0. , 0. ],
       [0. , 0. ],
       [0. , 0. ]])

In [91]:
print(np.corrcoef(rating_price[:,0], rating_price[:,1]))

[[1.       0.046601]
 [0.046601 1.      ]]


#### Pandas
In the AppleStore data some colmns are numeric and some are strings. When we read it as list of lists, or as NumPy array we need to subset or slice the dataset to convert one colmns into float in order to do numeric operations. That needs more coding. Cleaning the dataset, like dropping duplicates, handling missing values is difficult in list or array method. Any kind of data file can be accessed with Pandas.

In [97]:
import pandas as pd

In [93]:
dict = {
"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98] }

In [94]:
brics = pd.DataFrame(dict)

In [95]:
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [96]:
# Keys have become column labels and values have become column values, column by column.

In [98]:
apps_data = pd.read_csv('AppleStore.csv')

In [99]:
apps_data 

id                                    track_name  size_bytes  \
0      284882215                                      Facebook   389879808   
1      389801252                                     Instagram   113954816   
2      529479190                                Clash of Clans   116476928   
3      420009108                                    Temple Run    65921024   
4      284035177                       Pandora - Music & Radio   130242560   
...          ...                                           ...         ...   
7192  1170406182  Shark Boom - Challenge Friends with your Pet   245415936   
7193  1069830936                           【謎解き】ヤミすぎ彼女からのメッセージ    16808960   
7194  1070052833                                    Go!Go!Cat!    91468800   
7195  1081295232   Suppin Detective: Expose their true visage!    83026944   
7196   977965019           みんなのお弁当 by クックパッド ~お弁当をレシピ付きで記録・共有~    51174400   

     currency  price  rating_count_tot  rating_count_ver  user_rating  \
0         USD    0.0           2974676               212          3.5   
1         USD    0.0           2161558              1289          4.5   
2         USD    0.0           2130805               579          4.5   
3         USD    0.0           1724546              3842          4.5   
4         USD    0.0           1126879              3594          4.0   
...       ...    ...               ...               ...          ...   
7192      USD    0.0                 0                 0          0.0   
7193      USD    0.0                 0                 0          0.0   
7194      USD    0.0                 0                 0          0.0   
7195      USD    0.0                 0                 0          0.0   
7196      USD    0.0                 0                 0          0.0   

      user_rating_ver      ver cont_rating        prime_genre  \
0                 3.5       95          4+  Social Networking   
1                 4.0    10.23         12+      Photo & Video   
2                 4.5  9.24.12          9+              Games   
3                 4.0    1.6.2          9+              Games   
4                 4.5    8.4.1         12+              Music   
...               ...      ...         ...                ...   
7192              0.0    1.0.9          4+              Games   
7193              0.0      1.2          9+               Book   
7194              0.0    1.1.2         12+              Games   
7195              0.0    1.0.3         12+      Entertainment   
7196              0.0    1.4.0          4+       Food & Drink   

      sup_devices.num  ipadSc_urls.num  lang.num  vpp_lic  
0                  37                1        29        1  
1                  37                0        29        1  
2                  38                5        18        1  
3                  40                5         1        1  
4                  37                4         1        1  
...               ...              ...       ...      ...  
7192               38                5         1        1  
7193               38                0         1        1  
7194               37                2         2        1  
7195               40                0         1        1  
7196               37                0         1        1  

[7197 rows x 16 columns]

In [100]:
apps_data.dtypes

id                    int64
track_name           object
size_bytes            int64
currency             object
price               float64
rating_count_tot      int64
rating_count_ver      int64
user_rating         float64
user_rating_ver     float64
ver                  object
cont_rating          object
prime_genre          object
sup_devices.num       int64
ipadSc_urls.num       int64
lang.num              int64
vpp_lic               int64
dtype: object

In [105]:
apps_data.isna()

id  track_name  size_bytes  currency  price  rating_count_tot  \
0     False       False       False     False  False             False   
1     False       False       False     False  False             False   
2     False       False       False     False  False             False   
3     False       False       False     False  False             False   
4     False       False       False     False  False             False   
...     ...         ...         ...       ...    ...               ...   
7192  False       False       False     False  False             False   
7193  False       False       False     False  False             False   
7194  False       False       False     False  False             False   
7195  False       False       False     False  False             False   
7196  False       False       False     False  False             False   

      rating_count_ver  user_rating  user_rating_ver    ver  cont_rating  \
0                False        False            False  False        False   
1                False        False            False  False        False   
2                False        False            False  False        False   
3                False        False            False  False        False   
4                False        False            False  False        False   
...                ...          ...              ...    ...          ...   
7192             False        False            False  False        False   
7193             False        False            False  False        False   
7194             False        False            False  False        False   
7195             False        False            False  False        False   
7196             False        False            False  False        False   

      prime_genre  sup_devices.num  ipadSc_urls.num  lang.num  vpp_lic  
0           False            False            False     False    False  
1           False            False            False     False    False  
2           False            False            False     False    False  
3           False            False            False     False    False  
4           False            False            False     False    False  
...           ...              ...              ...       ...      ...  
7192        False            False            False     False    False  
7193        False            False            False     False    False  
7194        False            False            False     False    False  
7195        False            False            False     False    False  
7196        False            False            False     False    False  

[7197 rows x 16 columns]

In [104]:
apps_data.isna().sum()

id                  0
track_name          0
size_bytes          0
currency            0
price               0
rating_count_tot    0
rating_count_ver    0
user_rating         0
user_rating_ver     0
ver                 0
cont_rating         0
prime_genre         0
sup_devices.num     0
ipadSc_urls.num     0
lang.num            0
vpp_lic             0
dtype: int64

#### summary statistics 

* continuous variable

In [106]:
apps_data['user_rating'].mean()

3.526955675976101

In [107]:
apps_data['user_rating'].mode()

0    4.5
Name: user_rating, dtype: float64

In [108]:
apps_data['user_rating'].median()

4.0

In [109]:
apps_data['user_rating'].std()

1.5179475936298683

#### Frequency table

In [110]:
apps_data['prime_genre'].value_counts()

prime_genre
Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248
Health & Fitness      180
Productivity          178
Social Networking     167
Lifestyle             144
Music                 138
Shopping              122
Sports                114
Book                  112
Finance               104
Travel                 81
News                   75
Weather                72
Reference              64
Food & Drink           63
Business               57
Navigation             46
Medical                23
Catalogs               10
Name: count, dtype: int64

In [160]:
### Reading SAARC

In [161]:
saarc = pd.read_csv("3a79e33b-0b7f-47c5-af75-3c9c7ddb3ba6_Data.csv")

In [162]:
saarc

Time Time Code Country Name  \
0                                               2023    YR2023  Afghanistan   
1                                               2023    YR2023   Bangladesh   
2                                               2023    YR2023       Bhutan   
3                                               2023    YR2023        India   
4                                               2023    YR2023     Maldives   
5                                               2023    YR2023    Sri Lanka   
6                                               2023    YR2023     Pakistan   
7                                               2023    YR2023        Nepal   
8                                                NaN       NaN          NaN   
9                                                NaN       NaN          NaN   
10                                               NaN       NaN          NaN   
11  Data from database: World Development Indicators       NaN          NaN   
12                          Last Updated: 07/01/2025       NaN          NaN   

   Country Code  \
0           AFG   
1           BGD   
2           BTN   
3           IND   
4           MDV   
5           LKA   
6           PAK   
7           NPL   
8           NaN   
9           NaN   
10          NaN   
11          NaN   
12          NaN   

   Population density (people per sq. km of land area) [EN.POP.DNST]  \
0                                                  ..                  
1                                                  ..                  
2                                                  ..                  
3                                                  ..                  
4                                                  ..                  
5                                                  ..                  
6                                                  ..                  
7                                                  ..                  
8                                                 NaN                  
9                                                 NaN                  
10                                                NaN                  
11                                                NaN                  
12                                                NaN                  

    Population, total [SP.POP.TOTL]  \
0                      4.145476e+07   
1                      1.714670e+08   
2                      7.863850e+05   
3                      1.438070e+09   
4                      5.259940e+05   
5                      2.203700e+07   
6                      2.475045e+08   
7                      2.969461e+07   
8                               NaN   
9                               NaN   
10                              NaN   
11                              NaN   
12                              NaN   

    GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]  \
0                                    2.266944   
1                                    5.775112   
2                                    4.882594   
3                                    9.190755   
4                                    4.726392   
5                                   -2.329848   
6                                   -0.039839   
7                                    1.982548   
8                                         NaN   
9                                         NaN   
10                                        NaN   
11                                        NaN   
12                                        NaN   

    GDP per capita (constant 2015 US$) [NY.GDP.PCAP.KD]  \
0                                          378.066303     
1                                         1885.377336     
2                                         3488.844491     
3                                         2270.905181     
4                                        11415.939509     
5                                         3964.919874     
6                 

In [163]:
saarc = saarc.iloc[:8, :]

In [170]:
saarc

Time Time Code Country Name Country Code  \
0  2023    YR2023  Afghanistan          AFG   
1  2023    YR2023   Bangladesh          BGD   
2  2023    YR2023       Bhutan          BTN   
3  2023    YR2023        India          IND   
4  2023    YR2023     Maldives          MDV   
5  2023    YR2023    Sri Lanka          LKA   
6  2023    YR2023     Pakistan          PAK   
7  2023    YR2023        Nepal          NPL   

  Population density (people per sq. km of land area) [EN.POP.DNST]  \
0                                                 ..                  
1                                                 ..                  
2                                                 ..                  
3                                                 ..                  
4                                                 ..                  
5                                                 ..                  
6                                                 ..                  
7                                                 ..                  

     population  GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]  \
0  4.145476e+07                                   2.266944   
1  1.714670e+08                                   5.775112   
2  7.863850e+05                                   4.882594   
3  1.438070e+09                                   9.190755   
4  5.259940e+05                                   4.726392   
5  2.203700e+07                                  -2.329848   
6  2.475045e+08                                  -0.039839   
7  2.969461e+07                                   1.982548   

   GDP per capita (constant 2015 US$) [NY.GDP.PCAP.KD]  \
0                                         378.066303     
1                                        1885.377336     
2                                        3488.844491     
3                                        2270.905181     
4                                       11415.939509     
5                                        3964.919874     
6                                        1616.396701     
7                                        1136.427693     

   GDP (current US$) [NY.GDP.MKTP.CD] Gini index [SI.POV.GINI]  
0                        1.715223e+10                       ..  
1                        4.374153e+11                       ..  
2                        3.019254e+09                       ..  
3                        3.638489e+12                       ..  
4                        6.590894e+09                       ..  
5                        8.371614e+10                       ..  
6                        3.378855e+11                       ..  
7                        4.104777e+10                       ..

In [165]:
saarc.dtypes

Time                                                                  object
Time Code                                                             object
Country Name                                                          object
Country Code                                                          object
Population density (people per sq. km of land area) [EN.POP.DNST]     object
Population, total [SP.POP.TOTL]                                      float64
GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]                            float64
GDP per capita (constant 2015 US$) [NY.GDP.PCAP.KD]                  float64
GDP (current US$) [NY.GDP.MKTP.CD]                                   float64
Gini index [SI.POV.GINI]                                              object
dtype: object

In [169]:
saarc = saarc.rename(columns = {"Population, total [SP.POP.TOTL]" : "population"})

In [129]:
#More renaming



In [ ]:
# Finding out summary statistics of a column




In [ ]:
# Adding new columns and changing a column value



In [132]:
brics_country = set(brics['country'].unique())

In [133]:
saarc_country = set(saarc['Country Name'].unique())

In [134]:
brics_country - saarc_country

{'Brazil', 'China', 'Russia', 'South Africa'}

In [135]:
saarc_country - brics_country

{'Afghanistan',
 'Bangladesh',
 'Bhutan',
 'Maldives',
 'Nepal',
 'Pakistan',
 'Sri Lanka'}

In [136]:
saarc_country & brics_country

{'India'}

In [137]:
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [152]:
brics['population'].mean() 

601.176

In [176]:
saarc['population_million'] = saarc['population']/1000000

In [177]:
saarc['population_million'].mean().round(2)

243.94

In [178]:
brics['population'].mean() == saarc['population_million'].mean().round(2)

False

In [179]:
brics['population'].mean() > saarc['population_million'].mean().round(2)

True

In [ ]:
### Missing values